namespace EEducationPlatform.EntityFrameworkCore;

public abstract class EEducationPlatformEntityFrameworkCoreTestBase : EEducationPlatformTestBase<EEducationPlatformEntityFrameworkCoreTestModule>
{

}
